# Store your OpenAI API key here
OPENAI_API_KEY = "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"
