# Store your OpenAI API key here
OPENAI_API_KEY = "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"
