# Store your OpenAI API key here
OPENAI_API_KEY = "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"
